language: java

before_install:
  - chmod +x ./gradlew

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN
    
branches:
  only:
    - master

script:
  - ./gradlew jacocoTestReport --stacktrace
  - ./gradlew sonarqube
