language: java

before_install:
  - chmod +x ./gradlew

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN

script:
  - ./gradlew jacocoTestReport --stacktrace
  - ./gradlew sonarqube
